
function foodFetch(userSearch) {

    // console.log('paramater passed into function---', userSearch)

    return fetch(`https://developers.zomato.com/api/v2.1/search?entity_id=1138&entity_type=city&q=${userSearch}&apikey=${food_key}`, {
        headers: {
            "Accept": "application/json"
        }
    })
        .then(r => r.json())
    // .then(result => {
    //     console.log(result.restaurants[6].restaurant.name)
    // })
}

let userInputLocation = document.querySelector("#food-search")

function foodHTML (test, i) {
    // console.log('test', test, 'i', i)
    // console.log('show me below html', test.restaurants[i].restaurant.name)
    return `
    <h3>${test.restaurants[i].restaurant.name}</h3>
    <h4>${test.restaurants[i].restaurant.location.address}</h4>
    <button id="save-food-button">Eat Here!</button>
    `
}

function foodHTMLToDom (infoHTML, element) {
    document.querySelector(`${element}`).innerHTML += infoHTML
}


// console.log('user input location---', userInputLocation)

document.querySelector("#food-button").addEventListener("click", () => {
    fetch(`https://developers.zomato.com/api/v2.1/search?entity_id=1138&entity_type=city&q=${userInputLocation.value}&apikey=${food_key}`, {
        headers: {
            "Accept": "application/json"
        }
    })
    .then( restData => restData.json())
    .then( rest => {
        
        //Loop through and pull name and address of first 10 results from search
        document.querySelector("#results").innerHTML = ""
 
        for(let i=0; i < 10; i++) {
            // console.log('first parameter', foodHTML(rest), 'i', i)

            foodHTMLToDom(foodHTML( rest, i ), "#results")

            
            
            // console.log(rest.restaurants[i].restaurant.name)
            // console.log(rest.restaurants[i].restaurant.location.address)
        }
        
        

        // console.log(rest)
        // console.log('list of restaurants - ', rest.restaurants)
        // console.log('list first index of restaurants - ',rest.restaurants[0])
        // console.log('list of first object in index of restaurants - ', rest.restaurants[0].restaurant)
        // console.log('list the name of the restaurant - ', rest.restaurants[0].restaurant.name)
    })
})

// console.log('value in the input field---', userInputLocation.value)

foodFetch(userInputLocation.value)














// let searchInput = document.querySelector("#meetups-search")  
//get a handle to access the text input field

// //when the search button is clicked, do the following
// document.querySelector("#meetups-button").addEventListener("click", () => {
//   let apiUrl = "https://www.eventbriteapi.com/v3/events/search/" //The Url provided by the API provider
//   let apiToken = app_keys_eventbrite.token 
//Required parameter to obtain the data--generated by the API provider
//   fetch(`${apiUrl}?q=${searchInput.value}&location.address=nashville&location.within=10mi&expand=venue&token=${apiToken}&start_date.keyword=this_week`) //Look for the data using the input provided by the User
//   .then( data => data.json()) //Take the promise object returned by the fetch statement and convert it to a promise object containing the data in a JSON format
//   .then( meetupInformation => { //Take the promise object containing the JSON data and feed it to the function

//     console.log('meetupinformation',meetupInformation);
//     console.log('meetupinformation.events[0]',meetupInformation.events[0]);
//     console.log('meetupinformation.events.length',meetupInformation.events.length);
//     console.log('meetupinformation.events[0].name',meetupInformation.events[0].name);
//     console.log('meetupinformation.events[0].namej.text',meetupInformation.events[0].name.text)
//     // document.querySelector("#search-results").innerHTML = ""  //Clear out the area (from any previous search results)
//     // AddFoodComponentToDom(createFoodSearchComponent(meetupInformation), "search-results") //Call a function and pass it the DOM location to add the information
//   })
// })











