// event listener for form
let searchInput = document.querySelector("#meetups-search")  //get a handle to access the text input field
//when the search button is clicked, do the following
document.querySelector("#meetups-button").addEventListener("click", () => {
  let apiUrl = "https://www.eventbriteapi.com/v3/events/search/" //The Url provided by the API provider
  let apiToken = app_keys_eventbrite.token //Required parameter to obtain the data--generated by the API provider
  fetch(`${apiUrl}?q=${searchInput.value}&location.address=nashville&location.within=10mi&expand=venue&token=${apiToken}&start_date.keyword=this_week`) //Look for the data using the input provided by the User
  .then( data => data.json()) //Take the promise object returned by the fetch statement and convert it to a promise object containing the data in a JSON format
  .then( meetupInformation => { //Take the promise object containing the JSON data and feed it to the function
    if (meetupInformation.events.length < 10) { //If there are less than 10 results...then do the following:

      for (i = 0; i < meetupInformation.events.length; i++) {

        console.log(`meetupInformation.events${i}.namej.text`,meetupInformation.events[i].name.text);
          if (meetupInformation.events[i].venue.address.address_1 !== null)
            console.log('meetupInformation.events${i}.venue.address.address_1',meetupInformation.events[i].venue.address.address_1);
          else
            console.log('No address entered');
      
      }

    }
    else {//If there are more than 10 results, then only show the first 10...

      for (i = 0; i < 10; i++) {

        console.log(`meetupInformation.events${i}.namej.text`,meetupInformation.events[i].name.text);
          if (meetupInformation.events[i].venue.address.address_1 !== null)
            console.log('meetupInformation.events${i}.venue.address.address_1',meetupInformation.events[i].venue.address.address_1);
          else
            console.log('No address entered');
      
      }
    }
    
    // document.querySelector("#search-results").innerHTML = ""  //Clear out the area (from any previous search results)
    // AddFoodComponentToDom(createFoodSearchComponent(meetupInformation), "search-results") //Call a function and pass it the DOM location to add the information
  })
})